// ─── Mock Data for Development ────────────────────────────
// Used when database is not configured

export const mockJobs = [
    {
        id: "job-1",
        title: "Senior React Developer",
        company: "Flipkart",
        location: "Bangalore, India",
        salary: "₹25-35 LPA",
        salaryMin: 2500000,
        salaryMax: 3500000,
        url: "https://example.com/job-1",
        source: "linkedin",
        description: "We're looking for a Senior React Developer to join our frontend team. You'll work on building next-generation e-commerce experiences used by millions of users daily.",
        skills: ["React", "TypeScript", "Next.js", "GraphQL", "Node.js"],
        jobType: "hybrid",
        experience: "senior",
        postedAt: new Date(Date.now() - 86400000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
    {
        id: "job-2",
        title: "Full Stack Engineer",
        company: "Razorpay",
        location: "Remote, India",
        salary: "₹20-30 LPA",
        salaryMin: 2000000,
        salaryMax: 3000000,
        url: "https://example.com/job-2",
        source: "naukri",
        description: "Join Razorpay's engineering team to build scalable payment infrastructure. Work across the stack with React, Node.js, and Go.",
        skills: ["React", "Node.js", "Go", "PostgreSQL", "Redis"],
        jobType: "remote",
        experience: "mid",
        postedAt: new Date(Date.now() - 172800000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
    {
        id: "job-3",
        title: "Frontend Lead",
        company: "CRED",
        location: "Bangalore, India",
        salary: "₹30-45 LPA",
        salaryMin: 3000000,
        salaryMax: 4500000,
        url: "https://example.com/job-3",
        source: "linkedin",
        description: "Lead CRED's frontend engineering team. Define architecture decisions, mentor engineers, and build premium fintech experiences.",
        skills: ["React", "TypeScript", "Architecture", "Leadership", "Performance"],
        jobType: "onsite",
        experience: "lead",
        postedAt: new Date(Date.now() - 259200000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
    {
        id: "job-4",
        title: "Backend Engineer — Payments",
        company: "PhonePe",
        location: "Pune, India",
        salary: "₹18-28 LPA",
        salaryMin: 1800000,
        salaryMax: 2800000,
        url: "https://example.com/job-4",
        source: "indeed",
        description: "Build reliable payment systems at scale. Work with Java, Spring Boot, and distributed systems handling millions of transactions.",
        skills: ["Java", "Spring Boot", "Kafka", "MySQL", "Microservices"],
        jobType: "hybrid",
        experience: "mid",
        postedAt: new Date(Date.now() - 345600000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
    {
        id: "job-5",
        title: "Product Manager — Growth",
        company: "Swiggy",
        location: "Bangalore, India",
        salary: "₹22-35 LPA",
        salaryMin: 2200000,
        salaryMax: 3500000,
        url: "https://example.com/job-5",
        source: "linkedin",
        description: "Drive growth for Swiggy's food delivery vertical. Own metrics, run experiments, and work cross-functionally with engineering and design.",
        skills: ["Product Management", "Analytics", "A/B Testing", "SQL", "Growth"],
        jobType: "hybrid",
        experience: "senior",
        postedAt: new Date(Date.now() - 432000000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
    {
        id: "job-6",
        title: "DevOps Engineer",
        company: "Zerodha",
        location: "Bangalore, India",
        salary: "₹20-30 LPA",
        salaryMin: 2000000,
        salaryMax: 3000000,
        url: "https://example.com/job-6",
        source: "company",
        description: "Manage infrastructure for India's largest stock broker. Work with Kubernetes, AWS, and Terraform at massive scale.",
        skills: ["Kubernetes", "AWS", "Terraform", "Docker", "CI/CD"],
        jobType: "onsite",
        experience: "mid",
        postedAt: new Date(Date.now() - 518400000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
    {
        id: "job-7",
        title: "Data Scientist",
        company: "Meesho",
        location: "Bangalore, India",
        salary: "₹15-25 LPA",
        salaryMin: 1500000,
        salaryMax: 2500000,
        url: "https://example.com/job-7",
        source: "naukri",
        description: "Build ML models for recommendations, pricing, and demand forecasting. Work with Python, TensorFlow, and Big Data tools.",
        skills: ["Python", "TensorFlow", "SQL", "Machine Learning", "Spark"],
        jobType: "hybrid",
        experience: "mid",
        postedAt: new Date(Date.now() - 604800000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
    {
        id: "job-8",
        title: "Mobile Engineer — React Native",
        company: "Dream11",
        location: "Mumbai, India",
        salary: "₹18-28 LPA",
        salaryMin: 1800000,
        salaryMax: 2800000,
        url: "https://example.com/job-8",
        source: "jsearch",
        description: "Build and scale Dream11's mobile apps used by 150M+ users. Deep expertise in React Native, performance optimization, and native modules.",
        skills: ["React Native", "TypeScript", "iOS", "Android", "Performance"],
        jobType: "hybrid",
        experience: "senior",
        postedAt: new Date(Date.now() - 691200000).toISOString(),
        scrapedAt: new Date().toISOString(),
        active: true,
    },
];

export const mockApplications = [
    {
        id: "app-1",
        userId: "demo-user",
        jobId: "job-1",
        status: "APPLIED" as const,
        notes: "Applied through LinkedIn. Referral from college friend.",
        appliedAt: new Date(Date.now() - 432000000).toISOString(),
        updatedAt: new Date(Date.now() - 432000000).toISOString(),
        job: mockJobs[0],
    },
    {
        id: "app-2",
        userId: "demo-user",
        jobId: "job-2",
        status: "IN_REVIEW" as const,
        notes: "HR replied. Technical round scheduled next week.",
        appliedAt: new Date(Date.now() - 864000000).toISOString(),
        updatedAt: new Date(Date.now() - 172800000).toISOString(),
        job: mockJobs[1],
    },
    {
        id: "app-3",
        userId: "demo-user",
        jobId: "job-3",
        status: "INTERVIEW" as const,
        notes: "System design round on Friday.",
        appliedAt: new Date(Date.now() - 1296000000).toISOString(),
        updatedAt: new Date(Date.now() - 86400000).toISOString(),
        job: mockJobs[2],
    },
    {
        id: "app-4",
        userId: "demo-user",
        jobId: "job-5",
        status: "REJECTED" as const,
        notes: "Position filled internally.",
        appliedAt: new Date(Date.now() - 1728000000).toISOString(),
        updatedAt: new Date(Date.now() - 259200000).toISOString(),
        job: mockJobs[4],
    },
    {
        id: "app-5",
        userId: "demo-user",
        jobId: "job-6",
        status: "OFFER" as const,
        notes: "Offer received! ₹28 LPA + ESOPs",
        appliedAt: new Date(Date.now() - 2160000000).toISOString(),
        updatedAt: new Date(Date.now() - 43200000).toISOString(),
        job: mockJobs[5],
    },
];

export const mockInterviews = [
    {
        id: "int-1",
        applicationId: "app-3",
        scheduledAt: new Date(Date.now() + 172800000).toISOString(),
        type: "technical",
        notes: "System design round — Design a scalable feed system",
        prepNotes: "Review: Load balancers, CDN caching, database sharding, fan-out strategies",
        reminded: false,
        application: mockApplications[2],
    },
    {
        id: "int-2",
        applicationId: "app-2",
        scheduledAt: new Date(Date.now() + 604800000).toISOString(),
        type: "video",
        notes: "Technical screening — DSA + React internals",
        prepNotes: "Brush up on: React fiber architecture, reconciliation, hooks internals, common DSA patterns",
        reminded: false,
        application: mockApplications[1],
    },
];

export const mockTrends = [
    { role: "Frontend Developer", location: "Bangalore", count: 342, change: 12, avgSalary: 2200000 },
    { role: "Backend Engineer", location: "Bangalore", count: 289, change: 8, avgSalary: 2400000 },
    { role: "Full Stack Engineer", location: "Remote", count: 256, change: 15, avgSalary: 2100000 },
    { role: "Product Manager", location: "Bangalore", count: 178, change: -5, avgSalary: 2800000 },
    { role: "DevOps Engineer", location: "Hyderabad", count: 134, change: 22, avgSalary: 2300000 },
    { role: "Data Scientist", location: "Bangalore", count: 198, change: -3, avgSalary: 2600000 },
    { role: "Mobile Developer", location: "Mumbai", count: 112, change: 7, avgSalary: 2000000 },
    { role: "ML Engineer", location: "Bangalore", count: 156, change: 28, avgSalary: 3000000 },
];

export const mockWatchlist = [
    { id: "wl-1", companyName: "Google", careerUrl: "https://careers.google.com", lastChecked: new Date().toISOString() },
    { id: "wl-2", companyName: "Microsoft", careerUrl: "https://careers.microsoft.com", lastChecked: new Date().toISOString() },
    { id: "wl-3", companyName: "Stripe", careerUrl: "https://stripe.com/jobs", lastChecked: null },
];

export const mockUser = {
    id: "demo-user",
    name: "Demo User",
    email: "demo@jobpulse.ai",
    image: null,
    phone: "+919876543210",
    preferredRole: "Full Stack Engineer",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Next.js"],
    experienceLevel: "senior",
    preferredLocation: "Bangalore, India",
    salaryMin: 2000000,
    salaryMax: 4000000,
    jobTypes: ["remote", "hybrid"],
    briefingTime: "08:00",
    timezone: "Asia/Kolkata",
    briefingEnabled: true,
    trendAlerts: true,
    reminderBefore: 120,
    onboarded: true,
};
